### ISSUE TITLE
Scsgate configurazione in home assistant

### ISSUE THREAD

**Issue by hoper83** [flavio/scsgate#2]
Ciao Flavio, ho provato a configurare il framework home assistant con scsgate ma non riesco ad impostare la giusta configurazione. Puoi aiutarmi?

**Comment by flavio** [comment]
Puoi fornire piu' dettagli?

**Comment by hoper83** [comment]
Mi potresti postare un esempio di configurazione per l'accensione di una luce? Come vanno impostati i parametri nel file configuration.yaml

**Comment by flavio** [comment]
Dentro al `configuration.yaml` di home-assistant ho una linea:

```yml
light: !include devices/lights.yaml
```

Per comodita' mi piace tenere i vari aspetti di home-assistant in file di configurazione specifici.

Il file `devices/lights.yaml` e' tipo:

```yml
- platform: scsgate
  devices:
    entryway:
      name: Entryway
      scs_id: '17'
    kitchen_cabinets:
      name: Kitchen Cabinets
      scs_id: '12'
# e cosi' via
```
